In [7]:
import cv2
# 读取图片。
img = cv2.imread("C:/Users/beichen/dataset/meihuameat/2.jpg");
# 转成灰度图片
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY);
cv2.imshow('title', img);
cv2.waitKey(0);
cv2.destroyAllWindows();
# 二值化
ret,img=cv2.threshold(img, 127, 255, cv2.THRESH_BINARY);

# 显示图像
cv2.imshow("title", img);
cv2.imwrite("C:/Users/beichen/dataset/bwimg/2.jpg", img)
# 进程不结束，一直保持显示状态
cv2.waitKey(0);
#销毁所有窗口
cv2.destroyAllWindows();


In [11]:
import cv2
img = cv2.imread("C:/Users/beichen/dataset/bwimg/2.jpg") # 读取二值图像文件
resized = cv2.resize(img, (666, 500), cv2.INTER_LINEAR) # 调整图像大小为128x128
print(resized) # 打印像素矩阵

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [12]:
import matplotlib.image as img
image = img.imread('C:/Users/beichen/dataset/bwimg/2.jpg') # 读取二值图像文件
print(image.shape) # 打印图像的形状，例如(317, 504, 3)
print(image) # 打印像素矩阵

(500, 666)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [17]:
from PIL import Image                   #使用PIL打开图片，方便转成矩阵的形式
import numpy as np                      #矩阵肯定要用到numpy
x=Image.open('C:/Users/beichen/dataset/bwimg/2.jpg')                  #打开图片
x.show()
data=np.asarray(x)                      #转换为矩阵
print(data)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [24]:
import numpy as np
from PIL import Image
img = Image.open('C:/Users/beichen/dataset/bwimg/2.jpg')
img = img.resize((32,32))#32x32的矩阵
img = img.convert("L")
 
img_new = img.point(lambda x:0 if x> 170 else 1)
arr = np.array(img_new)
for i in range(arr.shape[0]):
    print(arr[i])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0]
[0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0]
[0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]
[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
[0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]
[0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1]
[0 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
[0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 1 1 1 1